name: test

on:
  push:
    branches:
      - 'master'
      - 'releases/v*'
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
      -
        name: Test
        uses: docker/bake-action@45c4bed4f4f232fb1466194a6cbdd7a18bcf0639 # v3
        with:
          targets: test
      -
        name: Upload coverage
        uses: codecov/codecov-action@ab904c41d6ece82784817410c45d8b8c02684457 # v3
        with:
          file: ./coverage/clover.xml
